apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-tutorial
  namespace: tutorial
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gitops-tutorial
  template:
    metadata:
      labels:
        app: gitops-tutorial
    spec:
      containers:
        - name: gitops-tutorial
          image: 'ghcr.io/protess/cicd-tut-source:ff50b8f'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-tutorial
  namespace: oid2023
spec:
  selector:
    app: gitops-tutorial
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
